name: deploy pip

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Docker 이미지 빌드, 푸시
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pip:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/pip:latest

      - name: EC2에 SSH 접속 후 배포
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull m${{ secrets.DOCKER_USERNAME }}/pip:latest
            docker stop pip || true
            docker rm pip || true
            docker run -d -p 3000:3000 --name pip ${{ secrets.DOCKER_USERNAME }}/pip:latest
